name: Test with ASAN

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running workflow'
        required: true

jobs:
  run_asan:
    runs-on: ubuntu-latest

    steps:
    - name: Log reason
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Reason for triggering: ${{ github.event.inputs.reason }}"

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install multilib packages
      run: sudo apt-get install gcc-multilib g++-multilib

    - name: Set ASAN-related environment variables
      run: echo "ADD_SANITIZER=address" >> $GITHUB_ENV

    - name: Install AFDKO and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt .
        pip freeze --all

    - name: Run tests
      run: pytest tests
